### PR TITLE
Fix windows symlink creation

### LINKED ISSUE #23: Symbolic Link fails on Windows
There is a know problem on windows when the creation of symbolic links are need. The UAC filter the symbolic link permission and don't let the user use it. You must open the console as administrator to use this resource.

## Steps to Reproduce:
1. Have a windows machine;
2. Open a console without admin rights;
2. Install plugin;
3. invoke local.

## Error:
PS C:\Jose\Dropbox\Github\AutoKariam> serverless invoke local -f hello
Serverless: Compiling with Typescript...
Using local tsconfig.json

  Error --------------------------------------------------

  EPERM: operation not permitted, symlink 'C:\Jose\Dropbox\Github\AutoKariam\node_modules' -> 'C:\Jose\Dropbox\Github\AutoKariam\.
build\node_modules'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: EPERM: operation not permitted, symlink 'C:\Jose\Dropbox\Github\AutoKariam\node_modules' -> 'C:\Jose\Dropbox\Github\AutoKariam\.build\node_modules'
    at Object.fs.symlinkSync (fs.js:961:18)
    at ServerlessPlugin.<anonymous> (C:\Jose\Dropbox\Github\AutoKariam\node_modules\serverless-plugin-typescript\dist\src\index.js:80:20)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Jose\Dropbox\Github\AutoKariam\node_modules\serverless-plugin-typescript\dist\src\index.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at PluginManager.invoke (C:\Users\José\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:217:22)
    at PluginManager.run (C:\Users\José\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:236:17)
    at variables.populateService.then (C:\Users\José\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:107:33)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Serverless.run (C:\Users\José\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:94:74)
    at serverless.init.then (C:\Users\José\AppData\Roaming\npm\node_modules\serverless\bin\serverless:30:50)

### Fonts:
https://github.com/jprichardson/node-fs-extra#windows
https://ember-cli.com/user-guide/#enabling-symlinks

### Fonts for Solution:
https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy-sync.md
https://nodejs.org/api/fs.html#fs_fs_symlinksync_target_path_type
https://stackoverflow.com/questions/39106516/node-fs-copy-a-folder

### PR DESCRIPTION
**Pull request by LadnovSasha**
Should fix #23, #89 , #100 

According to the [docs](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_symlink_target_path_type_callback) on windows we should define symlink type

Due to inactivity I am closing this PR because it goes from master (i am planning to publish it), instead I've created the same pull request in #109 

**Fork with fixes published here:** https://github.com/LadnovSasha/serverless-plugin-typescript

### CODE REVIEW

**Review by ThomasVuillaume — APPROVED** [review]
Just tested with Window 10 in Developper Mode, with Node 8.12, serverless@1.31.0 / serverless-plugin-typescript@1.1.5, running the shell in Administrator mode, and it worked.

**Comment by LadnovSasha** [comment]
Hope this will be merged some day 🤞

**Comment by ThomasVuillaume** [comment]
> 
> 
> Hope this will be merged some day 🤞

Yeah, @schickling if you have any news about that. In the meantime, I'm forking this with your patch @LadnovSasha

**Comment by ross2411** [comment]
Can someone please pull this in because it's causing me issues.

**Comment by francoislg** [comment]
I fixed it by using `ThomasVuillaume/serverless-plugin-typescript#master` as a dependency...

When will this be merged...?

**Comment by ThomasEg** [comment]
Please pull this, it solves the problem(as long as you run it as admin at least)...

(i've testede the ThomasVuillaume/serverless-plugin-typescript#master version)

**Comment by aarym** [comment]
Please could this get accepted as having to do a work around using another package cloned from this.

**Comment by ThomasVuillaume** [comment]
Seems Prisma doesn't like Windows devs :D

(Psst, i've got a Linux too)

**Comment by LadnovSasha** [comment]
I've published fork to npm, if someoune interested https://github.com/LadnovSasha/serverless-plugin-typescript

**Comment by jonasduever** [comment]
Using a fork for such a "small" and easy-to-fix issue is not an adequate solution for me. :/
(Though I understand that you don't want to wait for a merge anymore.)

_Edit:_ But since this project seems to be unmaintained anyway, it's maybe the only solution.

**Comment by LadnovSasha** [comment]
@jonasduever you can see in #130 that price is still present

**Comment by dortega3000** [comment]
Not a lot of responses from prisma, I will try their slack channel. If not will fork and publish as a new serverless plugin thats actually updated!

**Comment by ThomasVuillaume** [comment]
Ok we'll wait for your info

**Comment by 4fthawaiian** [comment]
.. is this still outstanding? I'm seeing this issue currently.

**Pull request closed without merging**
